### ISSUE TITLE
Set up technical environment

### ISSUE THREAD

**Issue by mbreton** [js-republic/ReDoc#1]
This epic aims to set up the complete technical foundation of the SGR project

- [x] #10 Set up Yarn
- [x] #2 Set up magic.io
- [x] #3 Set up linter
- [x] #12 Set up ES6 -> ES5 compilation
- [x] #11 Set up AVA
- [x] #13 Set up CI
